
const imageUrls = [
    '/images_a/1.jpg',
    '/images_a/2.jpg',
    '/images_a/3.jpg',
    '/images_a/4.jpg',
    '/images_a/5.jpg',
    '/images_a/6.jpg',
    '/images_a/7.jpg',
    '/images_a/8.jpg',
    '/images_a/9.jpg',
    '/images_a/10.jpg',
    '/images_a/11.jpg',
    '/images_a/12.jpg',
    '/images_a/13.jpg',
    '/images_a/14.jpg',
    '/images_a/15.jpg',
    '/images_a/16.jpg',
    '/images_a/17.jpg',
    '/images_a/18.jpg',
    '/images_a/19.jpg',
    '/images_a/20.jpg',
    '/images_a/21.jpg',
    '/images_a/22.jpg',
    '/images_a/23.jpg',
    '/images_a/24.jpg',
    '/images_a/25.jpg',
    '/images_a/26.jpg',
    '/images_a/27.jpg',
    '/images_a/28.jpg',
    '/images_a/29.jpg',
    '/images_a/30.jpg',
    '/images_a/31.jpg'
  ];
  
  export default imageUrls;